# Generated by Django 5.2.8 on 2025-12-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.FloatField()),
                ('job_level', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='SalaryEntry',
        ),
    ]
